### PR TITLE
Added PR Validator GitHub Workflow

### LINKED ISSUE #42: Adding github action workflow for PR validation
**The workflow checks consist of following steps-**

- Should check for the PR Description in the pull request
- Check for the issue number, if the PR is not addressing any issue it should include `Fixes #NEW`

@tanishaness
Pls assign me this issue give me labels like gssoc-extd,hacktoberfest,level3

### PR DESCRIPTION
**Pull request by ygowthamr**
**What i have done :**
 - Solved Adding GitHub action workflow for PR validation

Fix #42

@tanishaness 
Pls add me labels like gssoc-extd,level3,hacktoberfest-accepted.

### CODE REVIEW

**Comment by ygowthamr** [comment]
@tanishaness 

Pls review my pr and merge it

**Comment by ygowthamr** [comment]
@tanishaness 

Pls review my pr and merge it

**Comment by sanjay-kv** [comment]
@tanishaness when you close the pr without any communication , it would confuse contributors. maybe in future please let contributor know why closing.

**Comment by ygowthamr** [comment]
@tanishaness 
Why you have closed this issue ?

**Pull request closed without merging**
