### PR TITLE
feat : Change the graph for a better visualization #22

### PR DESCRIPTION
**Pull request by Ananya-vastare**
The graph was connected to a database . The database used was mysql 
heatmap_20241008_213126

### CODE REVIEW

**Comment by Ananya-vastare** [comment]
@tanishaness I have made the changes couldn't upload the video please excuse that . Thank you

**Review by tanishaness — CHANGES_REQUESTED** [review]
i think the data should be related to the times when student looked up down right left and it should be connected to the file which is executing this function of identifying the lookup down etc...
eg looked right for most of the time will be flagged cheating after reviewing in the graph

**Comment by Ananya-vastare** [comment]
Okay will do that

**Comment by Ananya-vastare** [comment]
Okay will make those changes

**Comment by Ananya-vastare** [comment]
@tanishaness I have made the changes please look into them thank you

**Pull request merged**
