### PR TITLE
Added LICENSE

### PR DESCRIPTION
**Pull request by smog-root**
Added MIT License!

### CODE REVIEW

**Comment by smog-root** [comment]
Why you not added labels to it???

**Comment by smog-root** [comment]
Add level1 with gssoc-ext and hacktoberfest-accepted!! It is not reflected in the leaderboard 😔

**Comment by tanishaness** [comment]
Oh I didnt notice, sorry for the delay

**Comment by smog-root** [comment]
@tanishaness assign PR this!!!! to me!!

**Pull request merged**
